version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080"
    working_dir: /
    volumes:
      - "./server/.env:/.env"
  nginx:
    build: front/
    ports:
      - "80:80"
